spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 86400000    # 24 hours
      refresh-token:
        expiration: 604800000 # 7 days

app:
  storage:
    bucket-name: portfolio-files
    max-file-size: 10485760   # 10MB