server:
  port: 8083
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/devcanvas_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
skill:
  categories: Languages,Frameworks/Libraries,DevOps/Tools,Domains

logging:
  level:
    org:
      springframework:
        security: DEBUG
